package dev.detekt.gradle.extensions

import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile

/**
 * Configuration for a custom report produced by a [dev.detekt.gradle.Detekt] task.
 *
 * A custom report is generated by a detekt rule set plugin that registers an output report with a
 * matching [reportId]. Both [reportId] and [outputLocation] must be set.
 */
abstract class CustomDetektReport {

    /** The identifier of the report. Must match the report id provided by a rule set plugin. */
    @get:Internal
    abstract var reportId: String?

    /** The file the report is written to. */
    @get:OutputFile
    abstract val outputLocation: RegularFileProperty

    override fun toString(): String = "CustomDetektReport(reportId=$reportId, outputLocation=$outputLocation)"
}
