[versions]
dokka = "1.9.20"
jacoco = "0.8.12"
kotlin = "2.0.0"
coroutines = "1.8.1"
ktlint = "1.3.1"
junit = "5.10.3"
slf4j = "2.0.13"

[libraries]
binaryCompatibilityValidator-plugin = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version = "0.16.2" }
breadmoirai-githubRelease-plugin = { module = "com.github.breadmoirai:github-release", version = "2.5.2" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradleNexus-publish-plugin = { module = "io.github.gradle-nexus:publish-plugin", version = "2.0.0" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# This version of AGP is used for testing and should be updated when new AGP versions are released to ensure detekt's
# Gradle plugin remains compatible.
android-gradle-plugin = "com.android.tools.build:gradle:8.5.1"

semver4j = "org.semver4j:semver4j:5.3.0"

kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradlePluginApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-mainKts = { module = "org.jetbrains.kotlin:kotlin-main-kts", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlinx-html = "org.jetbrains.kotlinx:kotlinx-html-jvm:0.11.0"
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# This represents the oldest AGP version that is supported by detekt.
# This should only be updated when updating the minimum version supported by detekt's Gradle plugin.
android-gradleApi = "com.android.tools.build:gradle-api:7.1.3"

ktlint-rulesetStandard = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint"  }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

junit-jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

sarif4k = "io.github.detekt.sarif4k:sarif4k:0.6.0"
assertj-core = "org.assertj:assertj-core:3.26.3"
classgraph = "io.github.classgraph:classgraph:4.8.174"
snakeyaml-engine = "org.snakeyaml:snakeyaml-engine:2.7"
jcommander = "org.jcommander:jcommander:1.83"
kctfork-core = { module = "dev.zacsweers.kctfork:core", version = "0.5.1" }
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"

[plugins]
# Do not declare plugins here - see https://github.com/detekt/detekt/pull/7088.
