name: Validate Gradle Wrapper
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d9336dac04dea2507a617466bc058a3def92b18b # v3
