name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  gradle:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 15]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper/
        key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/modules-2
        key: cache-dependencies-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'detekt-bom/build.gradle.kts', 'buildSrc/build.gradle.kts', 'settings.gradle.kts') }}
    - name: Cache Gradle Build Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/build-cache-1
        key: cache-build-${{ matrix.os }}-${{ matrix.jdk }}-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
    - name: Build detekt
      run: ./gradlew build moveJarForIntegrationTest -x detekt
    - name: Run detekt-cli --help
      run: java -jar ./build/detekt-cli-all.jar --help
    - name: Run detekt-cli with argsfile
      run: java -jar ./build/detekt-cli-all.jar "@./config/detekt/argsfile"
    - name: Verify Generated Detekt Config File
      if: ${{ matrix.jdk == '11' && matrix.os == 'ubuntu-latest' }}
      run: ./gradlew verifyGeneratorOutput
    - name: Cleanup Gradle Cache
      # https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

  compile-test-snippets:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper/
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/modules-2
          key: cache-dependencies-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'detekt-bom/build.gradle.kts', 'buildSrc/build.gradle.kts', 'settings.gradle.kts') }}
      - name: Cache Gradle Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/build-cache-1
          key: cache-compile-test-snippets-ubuntu-latest-11-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build and compile test snippets
        run: ./gradlew test -x ":detekt-gradle-plugin:test" -Pcompile-test-snippets=true
      - name: Cleanup Gradle Cache
        # https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
